export const ADICIONA_PROJETO = 'ADICIONA_PROJETO';
export const ALTERA_PROJETO = 'ALTERA_PROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';

export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS';

export const ADICIONA_TAREFA = 'ADICIONA_TAREFA';
export const ALTERA_TAREFA = 'ALTERA_TAREFA';
export const REMOVE_TAREFA = 'REMOVE_TAREFA';

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';

export const NOTIFICAR = 'NOTIFICAR';